meta_product_name: "Sportify"
meta_title: "Sportify - Find your sporting partner"
meta_description: "The app for all you sporting and social needs"
meta_image: "cover.png" # should exist in `app/assets/images/`
