meta_product_name: "Sportify"
meta_title: "Sportify - Meet you sporting buddy"
meta_description: "Sports are your passion? Nobody to play with? Sportify is the app for you. Find new activities in your city, meet new people, have fun!"
meta_image: "cover.png" # should exist in `app/assets/images/`
